use_frameworks!

platform :ios, '10.0'

target 'SampleTableView_Example' do
  pod 'SampleTableView', :path => '../'

  target 'SampleTableView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
